### ISSUE TITLE
에러코드 보고

### ISSUE THREAD

**Issue by darkcrash80** [yangparing/yangpa#1]
1x [ADDON_ACTION_FORBIDDEN] 애드온 'Yangpa' 보호된 함수 호출 'UseToy()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `UseToy'
...faceBlizzard_Collections\Blizzard_ToyBox.lua:145: in function `ToySpellButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:
nil
=============================================================
14x [ADDON_ACTION_BLOCKED] 애드온 'Yangpa' 보호된 함수 호출 '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function `Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function `SetMapAreaID'
FrameXML\WorldMapFrame.lua:1368: in function `WorldMapFrame_Update'
FrameXML\WorldMapFrame.lua:2955: in function `WorldMapFrame_UpdateMap'
FrameXML\WorldMapFrame.lua:460: in function <FrameXML\WorldMapFrame.lua:444>
[C]: in function `SetMapToCurrentZone'
FrameXML\WorldMapFrame.lua:390: in function <FrameXML\WorldMapFrame.lua:369>
[C]: in function `Show'
FrameXML\UIParent.lua:2441: in function `SetUIPanel'
FrameXML\UIParent.lua:2243: in function `ShowUIPanel'
FrameXML\UIParent.lua:2151: in function <FrameXML\UIParent.lua:2147>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2935: in function `ShowUIPanel'
FrameXML\UIParent.lua:2919: in function `ToggleFrame'
FrameXML\WorldMapFrame.lua:267: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
InCombatSkipped

**Comment by yangparing** [comment]
These bugs occur because the parent arguments are not properly inherited. I think Yanppa add-ons seem to malfunction when trying to hide a protected function. But I could not find them. Currently I do not play games. Perhaps the bug fix will be fixed in the next major patch, and I will analyze taint logs to find a solution. Unfortunately, Blizzard is planning a major overhaul of the Protected API, it can be difficult to solve the problem.
